// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ThetaDesk.Data;

#nullable disable

namespace ThetaDesk.Data.Migrations
{
    [DbContext(typeof(ThetaDeskDbContext))]
    [Migration("20260701210655_WeeklyCompounding")]
    partial class WeeklyCompounding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ThetaDesk.Domain.Entities.Adjustment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Automated")
                        .HasColumnType("boolean");

                    b.Property<string>("GreeksAfterJson")
                        .HasColumnType("text");

                    b.Property<string>("GreeksBeforeJson")
                        .HasColumnType("text");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid");

                    b.Property<string>("TriggerReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.ToTable("Adjustments");
                });

            modelBuilder.Entity("ThetaDesk.Domain.Entities.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Acknowledged")
                        .HasColumnType("boolean");

                    b.Property<Guid>("FundId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RaisedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FundId");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("ThetaDesk.Domain.Entities.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AfterJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("AtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("text");

                    b.Property<Guid>("FundId")
                        .HasColumnType("uuid");

                    b.Property<string>("HashPrev")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FundId", "AtUtc");

                    b.ToTable("AuditLog");
                });

            modelBuilder.Entity("ThetaDesk.Domain.Entities.Fund", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CashBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("CurrentNav")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("DrawdownStopPct")
                        .HasColumnType("numeric");

                    b.Property<int>("LotSize")
                        .HasColumnType("integer");

                    b.Property<decimal>("MaxMarginUtilPct")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MonthlyTargetPct")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PerPositionMaxLoss")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ProfitTakePct")
                        .HasColumnType("numeric");

                    b.Property<decimal>("StartingCapital")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Funds");
                });

            modelBuilder.Entity("ThetaDesk.Domain.Entities.GreeksSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Delta")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Gamma")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Iv")
                        .HasColumnType("numeric");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Rho")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("TakenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Theta")
                        .HasColumnType("numeric");

                    b.Property<decimal>("UnderlyingSpot")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Vega")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("PositionId", "TakenAtUtc");

                    b.ToTable("GreeksSnapshots");
                });

            modelBuilder.Entity("ThetaDesk.Domain.Entities.Instrument", b =>
                {
                    b.Property<long>("InstrumentToken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("InstrumentToken"));

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<int>("LotSize")
                        .HasColumnType("integer");

                    b.Property<string>("OptionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Strike")
                        .HasColumnType("numeric");

                    b.Property<string>("TradingSymbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("InstrumentToken");

                    b.ToTable("Instruments");
                });

            modelBuilder.Entity("ThetaDesk.Domain.Entities.MarginSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Exposure")
                        .HasColumnType("numeric");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Span")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.Property<decimal>("UtilisationPct")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("PositionId")
                        .IsUnique();

                    b.ToTable("MarginSnapshots");
                });

            modelBuilder.Entity("ThetaDesk.Domain.Entities.NavSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("AsOf")
                        .HasColumnType("date");

                    b.Property<decimal>("Charges")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DailyPnl")
                        .HasColumnType("numeric");

                    b.Property<Guid>("FundId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("MonthToDatePct")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Nav")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("FundId", "AsOf")
                        .IsUnique();

                    b.ToTable("NavSnapshots");
                });

            modelBuilder.Entity("ThetaDesk.Domain.Entities.OptionLeg", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CurrentPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("EntryPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<long>("InstrumentToken")
                        .HasColumnType("bigint");

                    b.Property<int>("Lots")
                        .HasColumnType("integer");

                    b.Property<string>("OptionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Qty")
                        .HasColumnType("integer");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Strike")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentToken");

                    b.HasIndex("PositionId");

                    b.ToTable("OptionLegs");
                });

            modelBuilder.Entity("ThetaDesk.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BrokerOrderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("FillPrice")
                        .HasColumnType("numeric");

                    b.Property<Guid>("OptionLegId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PlacedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Slippage")
                        .HasColumnType("numeric");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OptionLegId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ThetaDesk.Domain.Entities.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AdjustTriggerDelta")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date");

                    b.Property<int>("EntryDte")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<Guid>("FundId")
                        .HasColumnType("uuid");

                    b.Property<string>("GttStopOrderId")
                        .HasColumnType("text");

                    b.Property<bool>("IsDefinedRisk")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MarginBlocked")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("MaxLoss")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("NetCredit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ProfitTakePct")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<Guid?>("ProposalId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("RealisedPnl")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("StopLossPremiumMult")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TargetExitDte")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnrealisedPnl")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FundId");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("ThetaDesk.Domain.Entities.ProposalLeg", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Delta")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<long>("InstrumentToken")
                        .HasColumnType("bigint");

                    b.Property<decimal>("MidPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("OptionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProposalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Strike")
                        .HasColumnType("numeric");

                    b.Property<string>("TradingSymbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProposalId");

                    b.ToTable("ProposalLegs");
                });

            modelBuilder.Entity("ThetaDesk.Domain.Entities.RiskLimit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FundId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Hard")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("LowerBound")
                        .HasColumnType("numeric");

                    b.Property<string>("Metric")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("UpperBound")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("FundId");

                    b.ToTable("RiskLimits");
                });

            modelBuilder.Entity("ThetaDesk.Domain.Entities.StrategyConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AdjustTriggerDelta")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<int>("EntryDteMax")
                        .HasColumnType("integer");

                    b.Property<int>("EntryDteMin")
                        .HasColumnType("integer");

                    b.Property<Guid>("FundId")
                        .HasColumnType("uuid");

                    b.Property<bool>("GttEnabled")
                        .HasColumnType("boolean");

                    b.Property<decimal>("GttPremiumPct")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ProfitTargetPct")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<decimal>("SizingPct")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TargetExitDte")
                        .HasColumnType("integer");

                    b.Property<decimal>("VixMax")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<decimal>("VixMin")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<bool>("WeeklyCompounding")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("FundId");

                    b.ToTable("StrategyConfigs");
                });

            modelBuilder.Entity("ThetaDesk.Domain.Entities.StrategyLeg", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Expiry")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OptionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StrategyConfigId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TargetDelta")
                        .HasPrecision(6, 4)
                        .HasColumnType("numeric(6,4)");

                    b.HasKey("Id");

                    b.HasIndex("StrategyConfigId");

                    b.ToTable("StrategyLegs");
                });

            modelBuilder.Entity("ThetaDesk.Domain.Entities.TradeProposal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AdjustTriggerDelta")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<decimal>("AtmIv")
                        .HasColumnType("numeric");

                    b.Property<int>("EntryDte")
                        .HasColumnType("integer");

                    b.Property<decimal>("ExpectedReturnPct")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<Guid>("FundId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("GeneratedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("GttEnabled")
                        .HasColumnType("boolean");

                    b.Property<decimal>("GttPremiumPct")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<decimal>("IndiaVix")
                        .HasColumnType("numeric");

                    b.Property<decimal>("IvRank")
                        .HasColumnType("numeric");

                    b.Property<int>("Lots")
                        .HasColumnType("integer");

                    b.Property<decimal>("MarginBlocked")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MarginUtilPct")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MaxLoss")
                        .HasColumnType("numeric");

                    b.Property<decimal>("NetCredit")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("PositionId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ProfitTargetPct")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<int>("Qty")
                        .HasColumnType("integer");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Score")
                        .HasColumnType("numeric");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TargetExitDte")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FundId");

                    b.HasIndex("PositionId")
                        .IsUnique();

                    b.ToTable("Proposals");
                });

            modelBuilder.Entity("ThetaDesk.Domain.Entities.VolatilitySnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AtmIv")
                        .HasColumnType("numeric");

                    b.Property<Guid>("FundId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("IndiaVix")
                        .HasColumnType("numeric");

                    b.Property<decimal>("IvPercentile")
                        .HasColumnType("numeric");

                    b.Property<decimal>("IvRank")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("TakenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FundId", "TakenAtUtc");

                    b.ToTable("VolatilitySnapshots");
                });

            modelBuilder.Entity("ThetaDesk.Domain.Entities.Adjustment", b =>
                {
                    b.HasOne("ThetaDesk.Domain.Entities.Position", "Position")
                        .WithMany("Adjustments")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");
                });

            modelBuilder.Entity("ThetaDesk.Domain.Entities.Alert", b =>
                {
                    b.HasOne("ThetaDesk.Domain.Entities.Fund", "Fund")
                        .WithMany("Alerts")
                        .HasForeignKey("FundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fund");
                });

            modelBuilder.Entity("ThetaDesk.Domain.Entities.AuditEntry", b =>
                {
                    b.HasOne("ThetaDesk.Domain.Entities.Fund", "Fund")
                        .WithMany("AuditLog")
                        .HasForeignKey("FundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fund");
                });

            modelBuilder.Entity("ThetaDesk.Domain.Entities.GreeksSnapshot", b =>
                {
                    b.HasOne("ThetaDesk.Domain.Entities.Position", "Position")
                        .WithMany("GreeksSnapshots")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");
                });

            modelBuilder.Entity("ThetaDesk.Domain.Entities.MarginSnapshot", b =>
                {
                    b.HasOne("ThetaDesk.Domain.Entities.Position", "Position")
                        .WithOne("MarginSnapshot")
                        .HasForeignKey("ThetaDesk.Domain.Entities.MarginSnapshot", "PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");
                });

            modelBuilder.Entity("ThetaDesk.Domain.Entities.NavSnapshot", b =>
                {
                    b.HasOne("ThetaDesk.Domain.Entities.Fund", "Fund")
                        .WithMany("NavSnapshots")
                        .HasForeignKey("FundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fund");
                });

            modelBuilder.Entity("ThetaDesk.Domain.Entities.OptionLeg", b =>
                {
                    b.HasOne("ThetaDesk.Domain.Entities.Instrument", "Instrument")
                        .WithMany("Legs")
                        .HasForeignKey("InstrumentToken")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThetaDesk.Domain.Entities.Position", "Position")
                        .WithMany("Legs")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instrument");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("ThetaDesk.Domain.Entities.Order", b =>
                {
                    b.HasOne("ThetaDesk.Domain.Entities.OptionLeg", "OptionLeg")
                        .WithMany("Orders")
                        .HasForeignKey("OptionLegId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OptionLeg");
                });

            modelBuilder.Entity("ThetaDesk.Domain.Entities.Position", b =>
                {
                    b.HasOne("ThetaDesk.Domain.Entities.Fund", "Fund")
                        .WithMany("Positions")
                        .HasForeignKey("FundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fund");
                });

            modelBuilder.Entity("ThetaDesk.Domain.Entities.ProposalLeg", b =>
                {
                    b.HasOne("ThetaDesk.Domain.Entities.TradeProposal", "Proposal")
                        .WithMany("Legs")
                        .HasForeignKey("ProposalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proposal");
                });

            modelBuilder.Entity("ThetaDesk.Domain.Entities.RiskLimit", b =>
                {
                    b.HasOne("ThetaDesk.Domain.Entities.Fund", "Fund")
                        .WithMany("RiskLimits")
                        .HasForeignKey("FundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fund");
                });

            modelBuilder.Entity("ThetaDesk.Domain.Entities.StrategyConfig", b =>
                {
                    b.HasOne("ThetaDesk.Domain.Entities.Fund", "Fund")
                        .WithMany("Strategies")
                        .HasForeignKey("FundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fund");
                });

            modelBuilder.Entity("ThetaDesk.Domain.Entities.StrategyLeg", b =>
                {
                    b.HasOne("ThetaDesk.Domain.Entities.StrategyConfig", "StrategyConfig")
                        .WithMany("Legs")
                        .HasForeignKey("StrategyConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StrategyConfig");
                });

            modelBuilder.Entity("ThetaDesk.Domain.Entities.TradeProposal", b =>
                {
                    b.HasOne("ThetaDesk.Domain.Entities.Fund", "Fund")
                        .WithMany("Proposals")
                        .HasForeignKey("FundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThetaDesk.Domain.Entities.Position", "Position")
                        .WithOne("Proposal")
                        .HasForeignKey("ThetaDesk.Domain.Entities.TradeProposal", "PositionId");

                    b.Navigation("Fund");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("ThetaDesk.Domain.Entities.VolatilitySnapshot", b =>
                {
                    b.HasOne("ThetaDesk.Domain.Entities.Fund", "Fund")
                        .WithMany("VolatilitySnapshots")
                        .HasForeignKey("FundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fund");
                });

            modelBuilder.Entity("ThetaDesk.Domain.Entities.Fund", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("AuditLog");

                    b.Navigation("NavSnapshots");

                    b.Navigation("Positions");

                    b.Navigation("Proposals");

                    b.Navigation("RiskLimits");

                    b.Navigation("Strategies");

                    b.Navigation("VolatilitySnapshots");
                });

            modelBuilder.Entity("ThetaDesk.Domain.Entities.Instrument", b =>
                {
                    b.Navigation("Legs");
                });

            modelBuilder.Entity("ThetaDesk.Domain.Entities.OptionLeg", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("ThetaDesk.Domain.Entities.Position", b =>
                {
                    b.Navigation("Adjustments");

                    b.Navigation("GreeksSnapshots");

                    b.Navigation("Legs");

                    b.Navigation("MarginSnapshot");

                    b.Navigation("Proposal");
                });

            modelBuilder.Entity("ThetaDesk.Domain.Entities.StrategyConfig", b =>
                {
                    b.Navigation("Legs");
                });

            modelBuilder.Entity("ThetaDesk.Domain.Entities.TradeProposal", b =>
                {
                    b.Navigation("Legs");
                });
#pragma warning restore 612, 618
        }
    }
}
